server:
  port: 8090
  tomcat:
    max-connections: 5000
spring:
  application:
    name: seckill-service
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 10.108.163.120:9300
  datasource:                            #?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    url: jdbc:mysql://127.0.0.1:3306/hm49?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: dxq5522565
#    filters: stat
#    initialSize: 2
#    maxActive: 300
#    maxWait: 60000
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validation-query: SELECT 1
#    test-while-idle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSiz: 200
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  rabbitmq:
    virtual-host: /leyou
    username: leyou #???这里有没有最前面的"/"
    password: leyou
    host: 10.108.163.120
    template:
      exchange: leyou.order.exchange
    publisher-confirms: true
  redis:
    host: 10.108.163.120
  jackson:
    default-property-inclusion: non_null # 配置json处理时忽略空值
  resources:
    add-mappings: true
    chain:
      enabled: true
      gzipped: true
      html-application-cache: true
    cache:
      period: 3600m

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true  #当你获取host时，返回的不是主机名，而是ip
    ip-address: 127.0.0.1
    lease-expiration-duration-in-seconds: 10 #10秒不发送九过期
    lease-renewal-interval-in-seconds: 5 #每隔5秒发一次心跳

ribbon:
  ConnectTimeout: 4000 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 熔断超时时长：10000ms

leyou:
  jwt:
    cookieName: LEYOU_TOKEN
    pubKeyPath: /Users/duanxiangqing/Desktop/leyoucode/rsa/rsa.pub # 公钥地址

      # ??? 有些配置可能还没配好
#spring:
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#mybatis:
#  mapper-locations: com.leyou.seckill.mapper