server:
  port: 8092
  tomcat:
    max-connections: 5000
spring:
  application:
    name: comments-service
  data:
    mongodb:
      host: 10.108.163.120
      database: spitdb #???这里需要看一下
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hm49?characterEncoding=UTF-8&useSSL=false
    username: root
    password: dxq5522565
#    driver-class-name: com.mysql.cj.jdbc.Driver  #这个地方为什么没有
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  rabbitmq:
    virtual-host: /leyou
    username: leyou
    password: leyou
    host: 10.108.163.120
  redis:
    host: 10.108.163.120
  jackson:
    default-property-inclusion: non_null # 配置json处理时忽略空值
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true  #当你获取host时，返回的不是主机名，而是ip
    ip-address: 127.0.0.1
    lease-expiration-duration-in-seconds: 10 #10秒不发送九过期
    lease-renewal-interval-in-seconds: 5 #每隔5秒发一次心跳
ribbon:
  ConnectTimeout: 4000 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数

#???这里为什么是2
leyou:
  worker:
    workerId: 2
    dataCenterId: 2
  jwt:
    cookieName: LEYOU_TOKEN
    pubKeyPath: /Users/duanxiangqing/Desktop/leyoucode/rsa/rsa.pub # 公钥地址
