server:
  port: 8083
spring:
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 10.108.163.120:9300
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    host: 10.108.163.120
    username: leyou
    password: leyou
    virtual-host: /leyou
#    template: #消费者只接收不发送 不需要配置模板
#      exchange: leyou.item.exchange

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
#    prefer-ip-address: true
#    ip-address: 127.0.0.1
#    instance-id: ${spring.application.name}:${server.port}